<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '';
echo '<head>';
echo '<title>Prostadine Discount Site</title>';
echo '<meta name="viewport" content="width=deivce-width,initial-scale=1.0">';
echo '<link rel="icon" type="image/x-icon" href="image/faviocn.png">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="top-head txt-cntr">';
echo '<div class="wrap-ppet">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try">';
echo '<h2 class="to-hed clr-1"><img src="image/logo.png" class="img-lg"></h2>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '<div class="wrap-ppet mr-top">';
echo '';
echo '</div>';
echo '<!---------main-top-ppet--------->';
echo '<div class="wrap-ppet myh">';
echo '<div class="main-top-ppet flx jus-1 al-cntr">';
echo '<div class="main-top-ppet-img txt-cntr">';
echo '<img src="image/mnspina.png" class="main-img">';
echo '<img src="image/rating1.png" class="main-imgs ">';
echo '';
echo '</div>';
echo '<div class="main-top-ppet-cont">';
echo '<p><span class="clr-2"><b>Prostadine</b></span> is a 100% natural and unique formula containing nine powerful natural ingredients that help to keep your prostate healthy. </p>';
echo '';
echo '<div class="txt-cntr">';
echo '<p class="main-tag">YOU SAVE <span class="clr-2"><b> $300</b></span> TODAY!</p>';
echo '<h1><b>Regular Price: <del> $99/per bottle</del></b></h1>';
echo '<h2 class="high-light">Only for: $49/per bottle + Free Shipping</h2>';
echo '<div class="cta-btn myh buttonBounce">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try" class="main-cta ">CLAIM YOUR DISCOUNT NOW!</a>';
echo '';
echo '</div>';
echo '<img src="image/review.png" class="mn-img">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!---------second sec--------->';
echo '<!----------why chosse------->';
echo '<div class="wrap-ppet">';
echo '<div class="v-custo-ppet">';
echo '<div class="strip-m-ppet txt-cntr myh">';
echo '<h2 class="strip-head-ppet clr-1">Why Choose Prostadine?</h2>';
echo '</div>';
echo '<div class="vr-cust-ppet flx jus-1 al-cntr myh">';
echo '<div class="vr-cust-ppeto-1 txt-cntr">';
echo '<img src="image/fda1.png" class="v-img-w">';
echo '<div class="v-cont-ppet">';
echo '<h3 class="v-cust-head" style="color:#05857d">100% All Natural</h3>';
echo '<p class="mt-0">All ingredients are pure, natural, and carefully sourced.</p>';
echo '</div>';
echo '</div>';
echo '<div class="vr-cust-ppeto-1 txt-cntr">';
echo '<div class="v-cont-ppet">';
echo '<img src="image/fda2.png" class="v-img-w">';
echo '<h3 class="v-cust-head" style="color:#05857d">Made In The USA</h3>';
echo '<p class="mt-0">It is manufactured on US soil.</p>';
echo '</div>';
echo '</div>';
echo '<div class="vr-cust-ppeto-1 txt-cntr">';
echo '<img src="image/fda3.png" class="v-img-w">';
echo '<div class="v-cont-ppet">';
echo '<h3 class="v-cust-head" style="color:#05857d">FDA Approved Facility</h3>';
echo '<p class="mt-0">It is manufactured according to the latest standards.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-----------what-is-------->';
echo '<div class="wrap-ppet">';
echo '<div class="what-is">';
echo '<div class="strip-m-ppet txt-cntr myh">';
echo '<h2 class="strip-head-ppet clr-1">What is Prostadine Supplement ?</h2>';
echo '</div>';
echo '<div class="what-box-ppet flx jus-1 al-cntr gaps">';
echo '<div class="what-img-ppet m-txt">';
echo '<img src="image/doctor.png" class="what-img-ppets">';
echo '</div>';
echo '<div class="what-cont-ppet">';
echo '<small style="color:red"> <b>August 2022 - New Scientific Discovery</b></small>';
echo '<p><b>Scientists Discover The Real Root Cause Of Prostate Problems</b></p>';
echo '';
echo '<p>A recent Harvard study draws attention to the hard water in the US which contains toxic minerals that can create a dangerous buildup inside the body if consumed for a longer period of time.';
echo '<br> As it turns out, hard water is found in the majority of US areas and, unfortunately, the government just closes its eyes on the fact that millions of Americans have improper tap water caused by poor and aging water pipe infrastructure.</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-----------price strip-------->';
echo '<div class="top-head txt-cntr">';
echo '<div class="wrap-ppet">';
echo '<h2 class="to-hed clr-1"><b>Limited Time Special Pricing - Act Now!</b></h2>';
echo '<h2 class="p-sub">Secure Your Reserved Bottles While Stocks Last</h2>';
echo '</div>';
echo '</div>';
echo '<div class="wrap-ppet">';
echo '<div class="price-s-ppet flx jus-1 al-cntr">';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p1.jpg" class="prce-img"></a>';
echo '</div>';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p6.jpg" class="prce-img"></a>';
echo '</div>';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p3.jpg" class="prce-img"></a>';
echo '</div>';
echo '</div>';
echo '<div class="red-strip txt-cntr myh">';
echo '<p class="red-war">WARNING : Stock levels are limited Accept your reserved bottle above NOW before your discount expires.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-------------ingredients-------->';
echo '<div class="wrap-ppet">';
echo '<div class="ingt">';
echo '<div class="strip-m-ppet txt-cntr myh">';
echo '<h2 class="strip-head-ppet clr-1">Key Ingredients Of Prostadine</h2>';
echo '</div>';
echo '<div class="ingt-key" style="text-align:center;">';
echo '<div class="ingt-str">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/sec-itg.jpg" class="gti-img"></a>';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/sec-itg-2.jpg" class="gti-img"></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!------------offer----------->';
echo '<div class="offer-sect">';
echo '<div class="wrap-ppet">';
echo '<div class="spcl-offer">';
echo '<h2 class="spcl-hed txt-cntr clr-1 ">Order 6 Bottles or 3 Bottles and Get 2 FREE Bonuses!</u>';
echo '</h2>';
echo '<div class="offer-box flx jus-1 al-cntr" style="margin-top:20px;">';
echo '<div class="offer-start txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/bonus1.png" class="gti-img"></a>';
echo '<h2 style="background-color:#000;color:#fff;padding:10px;">BONUS #1 - KIDNEY RESTORE</h2>';
echo '<h3 style="color:#ff0000;">Retail Price - <del>$79</del> Today: FREE</h3>';
echo '<p>Kickstart your Prostadine journey and start cleansing your kidneys naturally with 7 unexpected spice and herb mixes that can do wonders in only two days.</p>';
echo '</div>';
echo '<div class="offer-start txt-cntr ">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/bonus2.png" class="gti-img"></a>';
echo '<h2 style="background-color:#000;color:#fff;padding:10px;">BONUS #2 - ROCKSTAR IN 7 DAYS</h2>';
echo '<h3 style="color:#ff0000;">Retail Price - <del>$79</del> Today: FREE</h3>';
echo '<p>Learn how to turn plain water into the most powerful natural the simple morning habit that boosts your stamina up to 41% and a whole lot more.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-----------price strip-------->';
echo '<div class="top-head txt-cntr">';
echo '<div class="wrap-ppet">';
echo '<h2 class="to-hed clr-1"><b>Limited Time Special Pricing - Act Now!</b></h2>';
echo '<h2 class="p-sub">Secure Your Reserved Bottles While Stocks Last</h2>';
echo '</div>';
echo '</div>';
echo '<div class="wrap-ppet">';
echo '<div class="price-s-ppet flx jus-1 al-cntr">';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p1.jpg" class="prce-img"></a>';
echo '</div>';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p6.jpg" class="prce-img"></a>';
echo '</div>';
echo '<div class="price-img-ppet txt-cntr">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try"><img src="image/p3.jpg" class="prce-img"></a>';
echo '</div>';
echo '</div>';
echo '<div class="red-strip txt-cntr myh">';
echo '<p class="red-war">WARNING : Stock levels are limited Accept your reserved bottle above NOW before your discount expires.</p>';
echo '</div>';
echo '</div>';
echo '<!-----------faq------------------->';
echo '<div class="bg-d">';
echo '<div class="wrap-ppet">';
echo '<div class="faq">';
echo '<div class="strip-m-ppet txt-cntr myh" style="padding:20px;">';
echo '<img src="image/mny-bk.png" class="mn-img">';
echo '</div>';
echo '<div class="faq-cont" style="text-align:center;">';
echo '<h2>Claim Your Discounted Prostadine Below While Stocks Last!</h2>';
echo '';
echo '<p style="color:#fff;">It’s very easy! Just click the button below now to go to our secure order checkout page, enter in your information, and they’ll immediately get to work shipping Prostadine right to your doorstep.</p>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--------------banner product--------->';
echo '<div class="wrap-ppet" style="padding:10px;">';
echo '<div class="shadow txt-cntr">';
echo '<div class="flx jus-1 al-cntr">';
echo '<div class="last-sect">';
echo '';
echo '<img src="image/prod_6_bottle.png" alt="product" class="ani-img mr-top">';
echo '</div>';
echo '<div class="last-sect" style="padding:10px;">';
echo '<h2 class="clr-3 das txt-cntr mr-top">Don't Wait Any Longer! Order Your Discounted bottle Now!</h2>';
echo '<h1>Regular Price: <del>$99/per bottle</del></h1>';
echo '<h1 class="clr-2">Only for: $49/per bottle</h1>';
echo '';
echo '<div class="cta-btn myh buttonBounce">';
echo '<a href="https://9255fety-1u03o7o09-kf1xgqf.hop.clickbank.net/?tid=try" class="main-cta ">CLAIM YOUR DISCOUNT NOW!</a>';
echo '</div>';
echo '<div class="tmre" id="countdown2"></div>';
echo '<img src="image/refs-logos.png" class="rfr-img" style="margin-top:30px;">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!----------footer------------->';
echo '<div class="foter" id="ghut" style="background-color:#efefef;padding:10px;">';
echo '<div class="wrap-ppet">';
echo '<div class="foter-con flx al-cntr jus-1">';
echo '<p>Copyright © 2023 </p>';
echo '<p class="foot-con"><a href="privacy7a29.html?gclid={gclid}&amp;wbraid={wbraid}&amp;gbraid={gbraid}&amp;ref_id={gclid}">Privacy Policy</a> | <a href="terms7a29.html?gclid={gclid}&amp;wbraid={wbraid}&amp;gbraid={gbraid}&amp;ref_id={gclid}">Terms & Conditions</a>                    | <a href="contact7a29.html?gclid={gclid}&amp;wbraid={wbraid}&amp;gbraid={gbraid}&amp;ref_id={gclid}">Contact Us</a></p>';
echo '</div>';
echo '<div class="fdas-con txt-cntr myh">';
echo '<p>FDA Compliance</p>';
echo '<small>Please note that the information we provide is not intended to replace consultation with a qualified  professional. They encourage you to inform your physician of changes you make to your lifestyle and discuss these with him or her. For questions or concerns about any conditions you may have, please contact your doctor.</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-------------timer script------>';
echo '<script>';
echo 'function countdown(elementName, minutes, seconds) {';
echo 'var element, endTime, hours, mins, msLeft, time;';
echo '';
echo 'function twoDigits(n) {';
echo 'return (n <= 9 ? "0" + n : n);';
echo '}';
echo '';
echo 'function updateTimer() {';
echo 'msLeft = endTime - (+new Date);';
echo 'if (msLeft < 1000) {';
echo 'element.innerHTML = "countdown's over!";';
echo '} else {';
echo 'time = new Date(msLeft);';
echo 'hours = time.getUTCHours();';
echo 'mins = time.getUTCMinutes();';
echo 'element.innerHTML = (hours ? hours + ':' + twoDigits(mins) : mins) + ':' + twoDigits(time.getUTCSeconds());';
echo 'setTimeout(updateTimer, time.getUTCMilliseconds() + 500);';
echo '}';
echo '}';
echo '';
echo 'element = document.getElementById(elementName);';
echo 'endTime = (+new Date) + 1000 * (60 * minutes + seconds) + 500;';
echo 'updateTimer();';
echo '}';
echo '';
echo 'countdown("countdown2", 100, 0);';
echo '</script>';
echo '</body>';
echo '';
echo '';
echo '</html>';
?>